# procesos que ha de fer la shiny
# Generated by OmopViewer 0.7.0
# Be careful editing this file

server <- function(input, output, session) {
  # summary ----
  output$summary_cdm_name <- shinyTree::renderTree(summaryCdmName(data))
  output$summary_packages <- shinyTree::renderTree(summaryPackages(data))
  output$summary_min_cell_count <- shinyTree::renderTree(summaryMinCellCount(data))
  output$summary_panels <- shinyTree::renderTree(summaryPanels(data))
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(
          fileName = file, logFile = NULL, logSqlPath = NULL
        )
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    summarise_omop_snapshot = FALSE,
    summarise_observation_period = FALSE,
    summarise_cohort_attrition = FALSE,
    summarise_characteristics = FALSE,
    summarise_log_file = FALSE,
    summarise_table = FALSE
  )


  # summarise_omop_snapshot -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_omop_snapshot <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_omop_snapshot_cdm_name,
      input$summarise_omop_snapshot_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_omop_snapshot, {
    if (updateButtons$summarise_omop_snapshot == TRUE) {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_omop_snapshot, {
    updateButtons$summarise_omop_snapshot <- FALSE
  })

  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotData <- shiny::eventReactive(input$update_summarise_omop_snapshot, {
    data[["summarise_omop_snapshot"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_omop_snapshot_cdm_name,
        .data$variable_name %in% input$summarise_omop_snapshot_variable_name
      )
  })
  getSummariseOmopSnapshotTable <- shiny::reactive({
    getSummariseOmopSnapshotData() |>
      OmopSketch::tableOmopSnapshot(
        header = input$summarise_omop_snapshot_table_header,
        groupColumn = input$summarise_omop_snapshot_table_group_column,
        hide = input$summarise_omop_snapshot_table_hide
      )
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )

  # summarise_observation_period -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_observation_period <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_observation_period_cdm_name,
      input$summarise_observation_period_observation_period_ordinal,
      input$summarise_observation_period_variable_name,
      input$summarise_observation_period_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_observation_period, {
    if (updateButtons$summarise_observation_period == TRUE) {
      output$update_message_summarise_observation_period <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_observation_period <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_observation_period, {
    updateButtons$summarise_observation_period <- FALSE
  })

  ## get summarise_observation_period data
  getSummariseObservationPeriodData <- shiny::eventReactive(input$update_summarise_observation_period, {
    data[["summarise_observation_period"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_observation_period_cdm_name,
        .data$variable_name %in% input$summarise_observation_period_variable_name,
        .data$estimate_name %in% input$summarise_observation_period_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$observation_period_ordinal %in% input$summarise_observation_period_observation_period_ordinal)
  })
  getSummariseObservationPeriodTable <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::tableObservationPeriod(
        header = input$summarise_observation_period_table_header,
        groupColumn = input$summarise_observation_period_table_group_column,
        hide = input$summarise_observation_period_table_hide
      )
  })
  output$summarise_observation_period_table <- gt::render_gt({
    getSummariseObservationPeriodTable()
  })
  output$summarise_observation_period_table_download <- shiny::downloadHandler(
    filename = paste0("table_obsevation_period.", input$summarise_observation_period_table_format),
    content = function(file) {
      gt::gtsave(getSummariseObservationPeriodTable(), file)
    }
  )
  getSummariseObservationPeriodPlot <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::plotObservationPeriod(
        variableName = input$summarise_observation_period_plot_variable,
        plotType = input$summarise_observation_period_plot_plot_type,
        facet = input$summarise_observation_period_plot_facet,
        colour = input$summarise_observation_period_plot_colour
      )
  })
  output$summarise_observation_period_plot <- shiny::renderUI({
    x <- getSummariseObservationPeriodPlot()
    renderInteractivePlot(x, input$summarise_observation_period_plot_interactive)
  })
  output$summarise_observation_period_plot_download <- shiny::downloadHandler(
    filename = "plot_observation_period.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseObservationPeriodPlot(),
        width = as.numeric(input$summarise_observation_period_plot_width),
        height = as.numeric(input$summarise_observation_period_plot_height),
        units = input$summarise_observation_period_plot_units,
        dpi = as.numeric(input$summarise_observation_period_plot_dpi)
      )
    }
  )

  # summarise_cohort_attrition -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_cohort_attrition <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_cohort_attrition_cdm_name,
      input$summarise_cohort_attrition_cohort_name,
      input$summarise_cohort_attrition_table_name,
      input$summarise_cohort_attrition_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_cohort_attrition, {
    if (updateButtons$summarise_cohort_attrition == TRUE) {
      output$update_message_summarise_cohort_attrition <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_cohort_attrition <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_attrition, {
    updateButtons$summarise_cohort_attrition <- FALSE
  })

  ## get summarise_cohort_attrition data
  getSummariseCohortAttritionData <- shiny::eventReactive(input$update_summarise_cohort_attrition, {
    data[["summarise_cohort_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_attrition_cdm_name,
        .data$variable_name %in% input$summarise_cohort_attrition_variable_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_attrition_cohort_name) |>
      omopgenerics::filterSettings(.data$table_name %in% input$summarise_cohort_attrition_table_name)
  })
  getSummariseCohortAttritionTable <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::tableCohortAttrition(
        header = input$summarise_cohort_attrition_table_header,
        groupColumn = input$summarise_cohort_attrition_table_group_column,
        hide = input$summarise_cohort_attrition_table_hide
      )
  })
  output$summarise_cohort_attrition_table <- gt::render_gt({
    getSummariseCohortAttritionTable()
  })
  output$summarise_cohort_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_attrition.", input$summarise_cohort_attrition_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortAttritionTable(), file)
    }
  )
  getSummariseCohortAttritionDiagram <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::plotCohortAttrition(
        show = input$summarise_cohort_attrition_diagram_show
      )
  })
  output$summarise_cohort_attrition_diagram <- DiagrammeR::renderGrViz({
    getSummariseCohortAttritionDiagram()
  })
  output$summarise_cohort_attrition_diagram_download <- shiny::downloadHandler(
    filename = "attrition_diagram.png",
    content = function(file) {
      svg <- DiagrammeRsvg::export_svg(getSummariseCohortAttritionDiagram())
      rsvg::rsvg_png(charToRaw(svg), file, width = input$summarise_cohort_attrition_diagram_width)
    }
  )

  # summarise_characteristics -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_characteristics <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_characteristics_cdm_name,
      input$summarise_characteristics_cohort_name,
      #input$summarise_characteristics_vaccination_campaign,
      input$summarise_characteristics_table_name,
      input$summarise_characteristics_variable_name,
      input$summarise_characteristics_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_characteristics, {
    if (updateButtons$summarise_characteristics == TRUE) {
      output$update_message_summarise_characteristics <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_characteristics <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_characteristics, {
    updateButtons$summarise_characteristics <- FALSE
  })

  ## get summarise_characteristics data
  getSummariseCharacteristicsData <- shiny::eventReactive(input$update_summarise_characteristics, {
    data[["summarise_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_characteristics_cdm_name,
        .data$variable_name %in% input$summarise_characteristics_variable_name,
        .data$estimate_name %in% input$summarise_characteristics_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_characteristics_cohort_name) |>
      omopgenerics::filterSettings(.data$table_name %in% input$summarise_characteristics_table_name) 
      #omopgenerics::filterStrata(.data$vaccination_campaign %in% input$summarise_characteristics_vaccination_campaign)
  })
  getSummariseCharacteristicsTable <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_characteristics_table_header,
        groupColumn = input$summarise_characteristics_table_group_column,
        hide = input$summarise_characteristics_table_hide
      )
  })
  output$summarise_characteristics_table <- gt::render_gt({
    getSummariseCharacteristicsTable()
  })
  output$summarise_characteristics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_characteristics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCharacteristicsTable(), file)
    }
  )
  getSummariseCharacteristicsPlot <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_characteristics_plot_plot_type,
        facet = input$summarise_characteristics_plot_facet,
        colour = input$summarise_characteristics_plot_colour
      )
  })
  
  output$summarise_characteristics_plot <- shiny::renderUI({
    x <- getSummariseCharacteristicsPlot()
    renderInteractivePlot(x, input$summarise_characteristics_plot_interactive)
  })
  output$summarise_characteristics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCharacteristicsPlot(),
        width = as.numeric(input$summarise_characteristics_plot_width),
        height = as.numeric(input$summarise_characteristics_plot_height),
        units = input$summarise_characteristics_plot_units,
        dpi = as.numeric(input$summarise_characteristics_plot_dpi)
      )
    }
  )

  # vaccinated eligibles in campaign, imported by me 
  output$summarise_choronology_plot_download <- shiny::downloadHandler(
    filename = "EligiblesVaccinatedInCampaign.png",
    content = function(file) {
      file.copy("www/EligiblesVaccinatedInCampaign.png", file)
    }
  )

  # summarise_log_file -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_log_file <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_log_file_cdm_name,
      input$summarise_log_file_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_log_file, {
    if (updateButtons$summarise_log_file == TRUE) {
      output$update_message_summarise_log_file <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_log_file <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_log_file, {
    updateButtons$summarise_log_file <- FALSE
  })

  ## get summarise_log_file data
  getSummariseLogFileData <- shiny::eventReactive(input$update_summarise_log_file, {
    data[["summarise_log_file"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_log_file_cdm_name,
        .data$variable_name %in% input$summarise_log_file_variable_name
      )
  })
  getSummariseLogFileTable <- shiny::reactive({
    getSummariseLogFileData() |>
      dplyr::filter(.data$estimate_name == "date_time") |>
      visOmopResults::visOmopTable(
        header = "cdm_name",
        hide = c("variable_level", "estimate_name")
      )
  })
  output$summarise_log_file_table <- gt::render_gt({
    getSummariseLogFileTable()
  })
  output$summarise_log_file_table_download <- shiny::downloadHandler(
    filename = paste0("table_log.", input$summarise_log_file_table_format),
    content = function(file) {
      gt::gtsave(getSummariseLogFileTable(), file)
    }
  )
  getSummariseLogFilePlot <- shiny::reactive({
    getSummariseLogFileData() |>
      dplyr::filter(.data$estimate_name == "elapsed_time") |>
      visOmopResults::barPlot(
        x = c("log_id", "variable_name"),
        y = "elapsed_time",
        colour = "cdm_name",
        position = input$summarise_log_file_plot_position
      )
  })
  output$summarise_log_file_plot <- shiny::renderUI({
    x <- getSummariseLogFilePlot()
    renderInteractivePlot(x, input$summarise_log_file_plot_interactive)
  })
  output$summarise_log_file_plot_download <- shiny::downloadHandler(
    filename = "plot_logs.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseLogFilePlot(),
        width = as.numeric(input$summarise_log_file_plot_width),
        height = as.numeric(input$summarise_log_file_plot_height),
        units = input$summarise_log_file_plot_units,
        dpi = as.numeric(input$summarise_log_file_plot_dpi)
      )
    }
  )

  # summarise_table -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_table <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_table_cdm_name,
      input$summarise_table_cohort_name,
      input$summarise_table_region,
      input$summarise_table_imd,
      input$summarise_table_sex,
      input$summarise_table_ethnicity,
      input$summarise_table_prior_dose,
      input$summarise_table_variable_name,
      input$summarise_table_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_table, {
    if (updateButtons$summarise_table == TRUE) {
      output$update_message_summarise_table <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_table <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_table, {
    updateButtons$summarise_table <- FALSE
  })

  ## get summarise_table data
  getSummariseTableData <- shiny::eventReactive(input$update_summarise_table, {
    data[["summarise_table"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_table_cdm_name,
        .data$variable_name %in% input$summarise_table_variable_name,
        .data$estimate_name %in% input$summarise_table_estimate_name
      ) |>
      omopgenerics::filterStrata(
        .data$region %in% input$summarise_table_region,
        .data$imd %in% input$summarise_table_imd,
        .data$sex %in% input$summarise_table_sex,
        .data$ethnicity %in% input$summarise_table_ethnicity,
        .data$prior_dose %in% input$summarise_table_prior_dose
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_table_cohort_name)
  })
  getSummariseTableTidy <- shiny::reactive({
    tidyDT(getSummariseTableData(), input$summarise_table_tidy_columns, input$summarise_table_tidy_pivot_estimates)
  })
  output$summarise_table_tidy <- DT::renderDT({
    getSummariseTableTidy()
  })
  output$summarise_table_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseTableData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseTableTable <- shiny::reactive({
    getSummariseTableData() |>
      simpleTable(
        header = input$summarise_table_table_header,
        group = input$summarise_table_table_group_column,
        hide = input$summarise_table_table_hide
      )
  })
  output$summarise_table_table <- gt::render_gt({
    getSummariseTableTable()
  })
  
  output$summarise_table_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$summarise_table_table_format),
    content = function(file) {
      gt::gtsave(getSummariseTableTable(), file)
    }
  )

## get strata plot 

  getSummariseTablePlot <- shiny::reactive({
    df <- getSummariseTableData() |>
      # omopgenerics::addSettings() |>
      omopgenerics::splitAll() |>
      dplyr::filter(
        .data$variable_name == "number subjects",
        .data$estimate_name == "count"
      ) |>
      dplyr::mutate(
        n = suppressWarnings(readr::parse_number(as.character(.data$estimate_value)))
      ) |>
      dplyr::filter(!is.na(.data$n))
    
    strata_cols <- intersect(
      input$summarise_table_plot_strata_columns,
      c("region", "imd", "sex", "ethnicity", "prior_dose")
    )
    
    shiny::req(length(strata_cols) > 0)
    
    if (isTRUE(input$summarise_table_plot_combine)) {
      df <- df |>
        dplyr::mutate(
          dplyr::across(dplyr::all_of(strata_cols), ~ dplyr::coalesce(as.character(.x), "NA"))
        ) |>
        tidyr::unite(
          col = "strata_label",
          dplyr::all_of(strata_cols),
          sep = "-",
          remove = FALSE
        ) |>
        dplyr::group_by(.data$strata_label, .data$cohort_name) |>
        dplyr::summarise(n = sum(.data$n, na.rm = TRUE), .groups = "drop")
      
      ggplot2::ggplot(df, ggplot2::aes(x = .data$strata_label, y = .data$n, fill = .data$strata_label)) +
        ggplot2::geom_col(show.legend = FALSE) +
        ggplot2::labs(x = "Strata", y = "n") +
        ggplot2::theme_minimal() +
        ggplot2::facet_wrap(~.data$cohort_name, scales = "free_x") +
        ggplot2::theme(
          axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)
        )
      
    } else {
      df <- df |>
        dplyr::select(dplyr::all_of(strata_cols), .data$n, .data$cohort_name) |>
        tidyr::pivot_longer(
          cols = dplyr::all_of(strata_cols),
          names_to = "strata_name",
          values_to = "strata_level"
        ) |>
        dplyr::filter(!is.na(.data$strata_level)) |>
        dplyr::group_by(.data$strata_name, .data$strata_level, .data$cohort_name) |>
        dplyr::summarise(n = sum(.data$n, na.rm = TRUE), .groups = "drop")
      
      ggplot2::ggplot(df, ggplot2::aes(x = .data$strata_level, y = .data$n, fill = .data$strata_level)) +
        ggplot2::geom_col(show.legend = FALSE) +
        ggplot2::facet_grid(cohort_name~strata_name, scales = "free_x") +
        ggplot2::labs(x = "Strata level", y = "n") +
        ggplot2::theme_minimal() +
        ggplot2::theme(
          axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)
        )
    }
  })
output$summarise_table_plot <- shiny::renderUI({
  x <- getSummariseTablePlot()
  renderInteractivePlot(x, input$summarise_table_plot_interactive)
})

output$summarise_table_plot_download <- shiny::downloadHandler(
  filename = "plot_strata.png",
  content = function(file) {
    ggplot2::ggsave(
      filename = file,
      plot = getSummariseTablePlot(),
      width = as.numeric(input$summarise_table_plot_width),
      height = as.numeric(input$summarise_table_plot_height),
      units = input$summarise_table_plot_units,
      dpi = as.numeric(input$summarise_table_plot_dpi)
    )
  }
)

## get coverage plots

getSummariseCoveragePlot <- function(input_cohort_name) {
  shiny::reactive({
    
    strata_cols_selected <- input[[paste0("summarise_coverage_plot_strata_columns_", input_cohort_name)]]
    print(strata_cols_selected)
    strata_cols_not <- setdiff(
      c("region", "imd", "sex", "ethnicity"),
      strata_cols_selected
    )
    
    strata_cols <- intersect(
      strata_cols_selected,
      c("region", "imd", "sex", "ethnicity")
    )
    
    shiny::req(length(strata_cols) > 0)
    
    df <- getSummariseTableData() |>
      omopgenerics::filterGroup(.data$cohort_name == input_cohort_name) |>
      print()|>
      dplyr::filter(
        .data$variable_name == "vaccinated",
        .data$estimate_name == "percentage"
      ) |>
      dplyr::filter(!is.na(.data$variable_name)) |>
      dplyr::mutate(
        estimate_value = suppressWarnings(
          readr::parse_number(as.character(.data$estimate_value)) / 100
        )
      ) |>
      dplyr::filter(!is.na(.data$estimate_value)) |>
      print() |>
      omopgenerics::filterStrata(.data$prior_dose > 2 & .data$prior_dose != "overall") |>
      omopgenerics::splitStrata() |>
      print()|>
      dplyr::filter(
        dplyr::if_all(dplyr::all_of(strata_cols_not), ~ .x == "overall")
      ) |>
      dplyr::mutate(
        dplyr::across(dplyr::all_of(strata_cols), ~ dplyr::coalesce(as.character(.x), "NA"))
      )
  
    
    if (isTRUE(input[[paste0("summarise_coverage_plot_combine_", input_cohort_name)]])) {
      
      df <- df |>
        tidyr::unite(
          col = "strata_label",
          dplyr::all_of(strata_cols),
          sep = "-",
          remove = FALSE
        ) |>
        dplyr::group_by(.data$strata_label, .data$prior_dose, .data$group_level) |>
        print()|>
        dplyr::summarise(vaccinated = sum(.data$estimate_value, na.rm = TRUE), .groups = "drop") 
      
        print(names(df))
      
      ggplot2::ggplot(df, ggplot2::aes(x = .data$strata_label, y = .data$vaccinated, fill = .data$strata_label)) +
        ggplot2::geom_col(show.legend = FALSE) +
        ggplot2::scale_y_continuous(labels = scales::percent_format()) +
        ggplot2::labs(x = "Strata", y = "Vaccinated") +
        ggplot2::theme_minimal() +
        ggplot2::facet_wrap(~ prior_dose, scales = "free_x") +
        ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))
      
    } else {
      
      df_long <- purrr::map_dfr(strata_cols, \(ii) {
        other_cols <- setdiff(strata_cols, ii)
        
        df |>
          dplyr::filter(
            dplyr::if_all(dplyr::all_of(other_cols), ~ .x == "overall")
          ) |>
          dplyr::transmute(
            prior_dose = .data$prior_dose,
            strata_name = ii,
            strata_level = .data[[ii]],
            vaccinated = .data$estimate_value
          )
      }) |>
        dplyr::group_by(.data$prior_dose, .data$strata_name, .data$strata_level) |>
        dplyr::summarise(vaccinated = mean(.data$vaccinated, na.rm = TRUE), .groups = "drop")
      
      ggplot2::ggplot(
        df_long,
        ggplot2::aes(x = .data$strata_level, y = .data$vaccinated, fill = .data$strata_level)
      ) +
        ggplot2::geom_col(show.legend = FALSE) +
        ggplot2::facet_grid(prior_dose ~ strata_name, scales = "free_x") +
        ggplot2::scale_y_continuous(labels = scales::percent_format()) +
        ggplot2::labs(x = "Strata level", y = "Vaccinated") +
        ggplot2::theme_minimal() +
        ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))
    }
  })
}

plot_a_2023 <- getSummariseCoveragePlot("a_2023")
plot_s_2024 <- getSummariseCoveragePlot("s_2024")
plot_a_2024 <- getSummariseCoveragePlot("a_2024")
plot_s_2025 <- getSummariseCoveragePlot("s_2025")

output$summarise_coverage_plot_a_2023 <- shiny::renderUI({
  x <- plot_a_2023()
  renderInteractivePlot(x, input$summarise_coverage_plot_interactive_a_2023)
})

output$summarise_coverage_plot_s_2024 <- shiny::renderUI({
  x <- plot_s_2024()
  renderInteractivePlot(x, input$summarise_coverage_plot_interactive_s_2024)
})

output$summarise_coverage_plot_a_2024 <- shiny::renderUI({
  x <- plot_a_2024()
  renderInteractivePlot(x, input$summarise_coverage_plot_interactive_a_2024)
})

output$summarise_coverage_plot_s_2025 <- shiny::renderUI({
  x <- plot_s_2025()
  renderInteractivePlot(x, input$summarise_coverage_plot_interactive_s_2025)
})

output$summarise_coverage_plot_download_a_2023 <- shiny::downloadHandler(
  filename = "plot_coverage_a_2023.png",
  content = function(file) {
    ggplot2::ggsave(
      filename = file,
      plot = plot_a_2023(),
      width = as.numeric(input$summarise_coverage_plot_width_a_2023),
      height = as.numeric(input$summarise_coverage_plot_height_a_2023),
      units = input$summarise_coverage_plot_units_a_2023,
      dpi = as.numeric(input$summarise_coverage_plot_dpi_a_2023)
    )
  }
)

output$summarise_coverage_plot_download_s_2024 <- shiny::downloadHandler(
  filename = "plot_coverage_s_2024.png",
  content = function(file) {
    ggplot2::ggsave(
      filename = file,
      plot = plot_s_2024(),
      width = as.numeric(input$summarise_coverage_plot_width_s_2024),
      height = as.numeric(input$summarise_coverage_plot_height_s_2024),
      units = input$summarise_coverage_plot_units_s_2024,
      dpi = as.numeric(input$summarise_coverage_plot_dpi_s_2024)
    )
  }
)

output$summarise_coverage_plot_download_a_2024 <- shiny::downloadHandler(
  filename = "plot_coverage_a_2024.png",
  content = function(file) {
    ggplot2::ggsave(
      filename = file,
      plot = plot_a_2024(),
      width = as.numeric(input$summarise_coverage_plot_width_a_2024),
      height = as.numeric(input$summarise_coverage_plot_height_a_2024),
      units = input$summarise_coverage_plot_units_a_2024,
      dpi = as.numeric(input$summarise_coverage_plot_dpi_a_2024)
    )
  }
)

output$summarise_coverage_plot_download_s_2025 <- shiny::downloadHandler(
  filename = "plot_coverage_s_2025.png",
  content = function(file) {
    ggplot2::ggsave(
      filename = file,
      plot = plot_s_2025(),
      width = as.numeric(input$summarise_coverage_plot_width_s_2025),
      height = as.numeric(input$summarise_coverage_plot_height_s_2025),
      units = input$summarise_coverage_plot_units_s_2025,
      dpi = as.numeric(input$summarise_coverage_plot_dpi_s_2025)
    )
  }
)

}