# Generated by OmopViewer 0.7.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "ohdsi_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    "COVID-19 Booster Campaigns Description"
  ),
  theme = bslib::bs_theme(brand = TRUE),
  shiny::tags$style(HTML(
    ".sticky-top-btn {
      position: sticky;
      top: 0;
      z-index: 20;
      background: var(--bs-body-bg);
    }"
  )),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("disease"),
    backgroundCard("background.md")
  ),
  bslib::nav_panel(
    title = "Summary",
    icon = shiny::icon("file-lines"),
    bslib::card(
      bslib::card_header("Explore results"),
      shiny::tags$div(
        class = "mb-2",
        shinyTree::shinyTree("summary_cdm_name", theme = "proton", themeIcons = FALSE),
        shinyTree::shinyTree("summary_packages", theme = "proton", themeIcons = FALSE),
        shinyTree::shinyTree("summary_min_cell_count", theme = "proton", themeIcons = FALSE),
        shinyTree::shinyTree("summary_panels", theme = "proton", themeIcons = FALSE)
      ),
      full_screen = TRUE
    )
  ),
  bslib::nav_menu(
    title = "OmopSketch",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Snapshot",
      icon = shiny::icon("camera"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_omop_snapshot",
                label = "Update content", 
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_omop_snapshot")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_omop_snapshot_cdm_name",
            label = "CDM name",
            choices = choices$summarise_omop_snapshot_cdm_name,
            selected = selected$summarise_omop_snapshot_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_omop_snapshot_variable_name",
            label = "Variable name",
            choices = choices$summarise_omop_snapshot_variable_name,
            selected = selected$summarise_omop_snapshot_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Snapshot",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_omop_snapshot_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_omop_snapshot_table_download", label = "Download table")
                ),
                class = "text-end" 
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = "estimate_name",
                      input_id = "summarise_omop_snapshot_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "cdm_name",
                      input_id = "summarise_omop_snapshot_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = "variable_name",
                      input_id = "summarise_omop_snapshot_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = "variable_level",
                      input_id = "summarise_omop_snapshot_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_omop_snapshot_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Observation period Summary",
      icon = shiny::icon("eye"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_observation_period",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_observation_period")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_cdm_name",
            label = "CDM name",
            choices = choices$summarise_observation_period_cdm_name,
            selected = selected$summarise_observation_period_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_observation_period_ordinal",
            label = "Observation period ordinal",
            choices = choices$summarise_observation_period_observation_period_ordinal,
            selected = selected$summarise_observation_period_observation_period_ordinal,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_variable_name",
            label = "Variable name",
            choices = choices$summarise_observation_period_variable_name,
            selected = selected$summarise_observation_period_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_observation_period_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_observation_period_estimate_name,
            selected = selected$summarise_observation_period_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("observation_period_ordinal", "variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_observation_period_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "cdm_name",
                      input_id = "summarise_observation_period_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = character(),
                      input_id = "summarise_observation_period_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = character(),
                      input_id = "summarise_observation_period_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_observation_period_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_observation_period_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_variable",
                    label = "Variable",
                    choices = c("Number subjects", "Records per person", "Duration in days", "Days to next observation period"),
                    selected = "Number subjects",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_plot_type",
                    label = "Plot type",
                    choices = c("boxplot", "barplot", "densityplot"),
                    selected = "barplot",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "observation_period_ordinal"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "observation_period_ordinal"),
                    selected = "observation_period_ordinal",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_observation_period_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "Objective 1: Cohort Characterisaton",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Cohort Attrition",
      icon = shiny::icon("layer-group"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_cohort_attrition",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_cohort_attrition")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_attrition_cdm_name",
            label = "CDM name",
            choices = choices$summarise_cohort_attrition_cdm_name,
            selected = selected$summarise_cohort_attrition_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_attrition_table_name",
            label = "Table name",
            choices = choices$summarise_characteristics_table_name,
            selected = selected$summarise_characteristics_table_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_attrition_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_cohort_attrition_cohort_name,
            selected = selected$summarise_cohort_attrition_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_cohort_attrition_variable_name",
            label = "Variable name",
            choices = choices$summarise_cohort_attrition_variable_name,
            selected = selected$summarise_cohort_attrition_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Attrition",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_attrition_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_attrition_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = "reason",
                      input_id = "summarise_cohort_attrition_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "variable_name",
                      input_id = "summarise_cohort_attrition_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_cohort_attrition_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = c("variable_level", "reason_id", "estimate_name", "cdm_version", "cohort_definition_id", "min_prior_observation", "table_name", "vocabulary_version"),
                      input_id = "summarise_cohort_attrition_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_cohort_attrition_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Diagram",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_cohort_attrition_diagram_width",
                    label = "Width (px)",
                    value = 2000
                  ),
                  shiny::downloadButton(outputId = "summarise_cohort_attrition_diagram_download", label = "Download Diagram")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_cohort_attrition_diagram_show",
                    label = "Show",
                    choices = c("subjects", "records"),
                    selected = c("subjects", "records"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                DiagrammeR::grVizOutput("summarise_cohort_attrition_diagram") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Cohort Characteristics",
      icon = shiny::icon("users-gear"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_characteristics",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_characteristics")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_cdm_name",
            label = "CDM name",
            choices = choices$summarise_characteristics_cdm_name,
            selected = selected$summarise_characteristics_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_table_name",
            label = "Table name",
            choices = choices$summarise_characteristics_table_name,
            selected = selected$summarise_characteristics_table_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_characteristics_cohort_name,
            selected = selected$summarise_characteristics_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          # shinyWidgets::pickerInput(
          #   inputId = "summarise_characteristics_vaccination_campaign",
          #   label = "Vaccination campaign",
          #   choices = choices$summarise_characteristics_vaccination_campaign,
          #   selected = selected$summarise_characteristics_vaccination_campaign,
          #   multiple = TRUE,
          #   options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          # ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_variable_name",
            label = "Variable name",
            choices = choices$summarise_characteristics_variable_name,
            selected = selected$summarise_characteristics_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_characteristics_estimate_name,
            selected = selected$summarise_characteristics_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Table Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("variable_name", "variable_level", "estimate_name"), # vaccination_campaign
                      input_id = "summarise_characteristics_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_characteristics_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = character(),
                      input_id = "summarise_characteristics_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = "table_name",
                      input_id = "summarise_characteristics_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_characteristics_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_characteristics_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_characteristics_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_plot_type",
                    label = "Plot type",
                    choices = c("boxplot", "barplot", "scatterplot"),
                    selected = "boxplot",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "cohort_name", "table_name"),
                    selected =c("cohort_name", "table_name"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                  inputId = "summarise_characteristics_plot_colour",
                  label = "Colour",
                  choices = c("cdm_name", "cohort_name", "table_name"),
                  selected =c("cohort_name", "table_name"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_characteristics_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Vaccinated Characteristics (eligibles)",
      icon = shiny::icon("compass"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_table",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_table")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_cdm_name",
            label = "CDM name",
            choices = choices$summarise_table_cdm_name,
            selected = selected$summarise_table_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_table_cohort_name,
            selected = selected$summarise_table_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_region",
            label = "Region",
            choices = choices$summarise_table_region,
            selected = selected$summarise_table_region,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_imd",
            label = "Imd",
            choices = choices$summarise_table_imd,
            selected = selected$summarise_table_imd,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_sex",
            label = "Sex",
            choices = choices$summarise_table_sex,
            selected = selected$summarise_table_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_ethnicity",
            label = "Ethnicity",
            choices = choices$summarise_table_ethnicity,
            selected = selected$summarise_table_ethnicity,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_prior_dose",
            label = "Prior dose",
            choices = choices$summarise_table_prior_dose,
            selected = selected$summarise_table_prior_dose,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_variable_name",
            label = "Variable name",
            choices = choices$summarise_table_variable_name,
            selected = selected$summarise_table_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_table_estimate_name,
            selected = selected$summarise_table_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left",
        ),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Stratification",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput("summarise_table_plot_width", "Width", 15),
                  shiny::numericInput("summarise_table_plot_height", "Height", 15),
                  shinyWidgets::pickerInput(
                    "summarise_table_plot_units", "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm", multiple = FALSE
                  ),
                  shiny::numericInput("summarise_table_plot_dpi", "DPI", 300),
                  shiny::downloadButton("summarise_table_plot_download", "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_table_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_table_plot_strata_columns",
                    label = "Strata to use",
                    choices = c("region", "imd", "sex", "ethnicity", "prior_dose"),
                    selected = c("sex", "ethnicity"),
                    multiple = TRUE,
                    options = list(
                      `actions-box` = TRUE,
                      size = 10,
                      `selected-text-format` = "count > 3"
                    )
                  ),
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_table_plot_combine",
                    label = "Combine selected strata",
                    value = TRUE
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_table_plot") |> shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Vaccination Chronology (eligibles)",
      icon = shiny::icon("users-gear"),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Vaccination Dates",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(
                  outputId = "summarise_choronology_plot_download",
                  label = "Download png"
                  )
                ),
              class = "text-end"
              ),
            shiny::tags$img(
              src = "EligiblesVaccinatedInCampaign.svg",
              width = "80%"
            )
          )  
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "Objective 2: Coverage",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Summarise Tables",
      icon = shiny::icon("compass"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_table",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_table")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_cdm_name",
            label = "CDM name",
            choices = choices$summarise_table_cdm_name,
            selected = selected$summarise_table_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_cohort_name",
            label = "CDM name",
            choices = choices$summarise_table_cdm_name,
            selected = selected$summarise_table_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_table_cohort_name,
            selected = selected$summarise_table_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_region",
            label = "Region",
            choices = choices$summarise_table_region,
            selected = selected$summarise_table_region,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_imd",
            label = "Imd",
            choices = choices$summarise_table_imd,
            selected = selected$summarise_table_imd,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_sex",
            label = "Sex",
            choices = choices$summarise_table_sex,
            selected = selected$summarise_table_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_ethnicity",
            label = "Ethnicity",
            choices = choices$summarise_table_ethnicity,
            selected = selected$summarise_table_ethnicity,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_prior_dose",
            label = "Prior dose",
            choices = choices$summarise_table_prior_dose,
            selected = selected$summarise_table_prior_dose,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_variable_name",
            label = "Variable name",
            choices = choices$summarise_table_variable_name,
            selected = selected$summarise_table_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_table_estimate_name,
            selected = selected$summarise_table_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left",
        ), 
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_table_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_table_tidy_columns",
                    label = "Columns",
                    choices = c("cdm_name", "region", "imd", "sex", "ethnicity", "prior_dose", "variable_name", "variable_level"),
                    selected = c("cdm_name", "region", "imd", "sex", "ethnicity", "prior_dose", "variable_name", "variable_level"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::checkboxInput(
                    inputId = "summarise_table_tidy_pivot_estimates",
                    label = "Pivot estimates",
                    value = TRUE
                  ),
                  position = "right"
                ),
                DT::DTOutput("summarise_table_tidy") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Table",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_table_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_table_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("cdm_name", "region", "imd", "sex", "ethnicity", "prior_dose", "variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_table_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = character(),
                      input_id = "summarise_table_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = character(),
                      input_id = "summarise_table_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = "prior_dose",
                      input_id = "summarise_table_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_table_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Plots Coverage",
      icon = shiny::icon("users-gear"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          bslib::card(
            class = "sticky-top-btn",
            bslib::card_body(
              shiny::actionButton(
                inputId = "update_summarise_table",
                label = "Update content",
                width = "100%"
              ),
              uiOutput(outputId = "update_message_summarise_table")
            )
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_cdm_name",
            label = "CDM name",
            choices = choices$summarise_table_cdm_name,
            selected = selected$summarise_table_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_region",
            label = "Region",
            choices = choices$summarise_table_region,
            selected = selected$summarise_table_region,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_imd",
            label = "Imd",
            choices = choices$summarise_table_imd,
            selected = selected$summarise_table_imd,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_sex",
            label = "Sex",
            choices = choices$summarise_table_sex,
            selected = selected$summarise_table_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_ethnicity",
            label = "Ethnicity",
            choices = choices$summarise_table_ethnicity,
            selected = selected$summarise_table_ethnicity,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_variable_name",
            label = "Variable name",
            choices = choices$summarise_table_variable_name,
            selected = selected$summarise_table_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_table_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_table_estimate_name,
            selected = selected$summarise_table_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left",
        ),
        bslib::navset_card_tab(

  bslib::nav_panel(
    title = "Autumn 2023",
    bslib::card(
      full_screen = TRUE,
      bslib::card_header(
        bslib::popover(
          shiny::icon("download"),
          shiny::numericInput("summarise_coverage_plot_width_a_2023", "Width", 15),
          shiny::numericInput("summarise_coverage_plot_height_a_2023", "Height", 15),
          shinyWidgets::pickerInput(
            "summarise_coverage_plot_units_a_2023", "Units",
            choices = c("px", "cm", "inch"),
            selected = "cm", multiple = FALSE
          ),
          shiny::numericInput("summarise_coverage_plot_dpi_a_2023", "DPI", 300),
          shiny::downloadButton("summarise_coverage_plot_download_a_2023", "Download plot")
        ),
        class = "text-end"
      ),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::materialSwitch(
            inputId = "summarise_coverage_plot_interactive_a_2023",
            label = "Interactive",
            value = TRUE
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_coverage_plot_strata_columns_a_2023",
            label = "Strata to use",
            choices = c("region", "imd", "sex", "ethnicity"),
            selected = c("sex", "ethnicity"),
            multiple = TRUE,
            options = list(
              `actions-box` = TRUE,
              size = 10,
              `selected-text-format` = "count > 3"
            )
          ),
          shinyWidgets::materialSwitch(
            inputId = "summarise_coverage_plot_combine_a_2023",
            label = "Combine selected strata",
            value = TRUE
          ),
          position = "right"
        ),
        shiny::uiOutput("summarise_coverage_plot_a_2023") |>
          shinycssloaders::withSpinner()
      )
    )
  ),

  bslib::nav_panel(
    title = "Spring 2024",
    bslib::card(
      full_screen = TRUE,
      bslib::card_header(
        bslib::popover(
          shiny::icon("download"),
          shiny::numericInput("summarise_coverage_plot_width_s_2024", "Width", 15),
          shiny::numericInput("summarise_coverage_plot_height_s_2024", "Height", 15),
          shinyWidgets::pickerInput(
            "summarise_coverage_plot_units_s_2024", "Units",
            choices = c("px", "cm", "inch"),
            selected = "cm", multiple = FALSE
          ),
          shiny::numericInput("summarise_coverage_plot_dpi_s_2024", "DPI", 300),
          shiny::downloadButton("summarise_coverage_plot_download_s_2024", "Download plot")
        ),
        class = "text-end"
      ),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::materialSwitch(
            inputId = "summarise_coverage_plot_interactive_s_2024",
            label = "Interactive",
            value = TRUE
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_coverage_plot_strata_columns_s_2024",
            label = "Strata to use",
            choices = c("region", "imd", "sex", "ethnicity"),
            selected = c("sex", "ethnicity"),
            multiple = TRUE,
            options = list(
              `actions-box` = TRUE,
              size = 10,
              `selected-text-format` = "count > 3"
            )
          ),
          shinyWidgets::materialSwitch(
            inputId = "summarise_coverage_plot_combine_s_2024",
            label = "Combine selected strata",
            value = TRUE
          ),
          position = "right"
        ),
        shiny::uiOutput("summarise_coverage_plot_s_2024") |>
          shinycssloaders::withSpinner()
      )
    )
  ),

  bslib::nav_panel(
    title = "Autumn 2024",
    bslib::card(
      full_screen = TRUE,
      bslib::card_header(
        bslib::popover(
          shiny::icon("download"),
          shiny::numericInput("summarise_coverage_plot_width_a_2024", "Width", 15),
          shiny::numericInput("summarise_coverage_plot_height_a_2024", "Height", 15),
          shinyWidgets::pickerInput(
            "summarise_coverage_plot_units_a_2024", "Units",
            choices = c("px", "cm", "inch"),
            selected = "cm", multiple = FALSE
          ),
          shiny::numericInput("summarise_coverage_plot_dpi_a_2024", "DPI", 300),
          shiny::downloadButton("summarise_coverage_plot_download_a_2024", "Download plot")
        ),
        class = "text-end"
      ),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::materialSwitch(
            inputId = "summarise_coverage_plot_interactive_a_2024",
            label = "Interactive",
            value = TRUE
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_coverage_plot_strata_columns_a_2024",
            label = "Strata to use",
            choices = c("region", "imd", "sex", "ethnicity"),
            selected = c("sex", "ethnicity"),
            multiple = TRUE,
            options = list(
              `actions-box` = TRUE,
              size = 10,
              `selected-text-format` = "count > 3"
            )
          ),
          shinyWidgets::materialSwitch(
            inputId = "summarise_coverage_plot_combine_a_2024",
            label = "Combine selected strata",
            value = TRUE
          ),
          position = "right"
        ),
        shiny::uiOutput("summarise_coverage_plot_a_2024") |>
          shinycssloaders::withSpinner()
      )
    )
  ),

  bslib::nav_panel(
    title = "Spring 2025",
    bslib::card(
      full_screen = TRUE,
      bslib::card_header(
        bslib::popover(
          shiny::icon("download"),
          shiny::numericInput("summarise_coverage_plot_width_s_2025", "Width", 15),
          shiny::numericInput("summarise_coverage_plot_height_s_2025", "Height", 15),
          shinyWidgets::pickerInput(
            "summarise_coverage_plot_units_s_2025", "Units",
            choices = c("px", "cm", "inch"),
            selected = "cm", multiple = FALSE
          ),
          shiny::numericInput("summarise_coverage_plot_dpi_s_2025", "DPI", 300),
          shiny::downloadButton("summarise_coverage_plot_download_s_2025", "Download plot")
        ),
        class = "text-end"
      ),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::materialSwitch(
            inputId = "summarise_coverage_plot_interactive_s_2025",
            label = "Interactive",
            value = TRUE
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_coverage_plot_strata_columns_s_2025",
            label = "Strata to use",
            choices = c("region", "imd", "sex", "ethnicity"),
            selected = c("sex", "ethnicity"),
            multiple = TRUE,
            options = list(
              `actions-box` = TRUE,
              size = 10,
              `selected-text-format` = "count > 3"
            )
          ),
          shinyWidgets::materialSwitch(
            inputId = "summarise_coverage_plot_combine_s_2025",
            label = "Combine selected strata",
            value = TRUE
          ),
          position = "right"
        ),
        shiny::uiOutput("summarise_coverage_plot_s_2025") |>
          shinycssloaders::withSpinner()
      )
    )
  )
)
      )
    )
  ),
  bslib::nav_panel(
    title = "Logs",
    icon = shiny::icon("clipboard-list"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_summarise_log_file",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_summarise_log_file")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_log_file_cdm_name",
          label = "CDM name",
          choices = choices$summarise_log_file_cdm_name,
          selected = selected$summarise_log_file_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_log_file_variable_name",
          label = "Variable name",
          choices = choices$summarise_log_file_variable_name,
          selected = selected$summarise_log_file_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Table Logs",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_log_file_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "summarise_log_file_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            gt::gt_output("summarise_log_file_table") |>
              shinycssloaders::withSpinner()
          )
        ),
        bslib::nav_panel(
          title = "Plot Timing",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::numericInput(
                  inputId = "summarise_log_file_plot_width",
                  label = "Width",
                  value = 15
                ),
                shiny::numericInput(
                  inputId = "summarise_log_file_plot_height",
                  label = "Height",
                  value = 15
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_log_file_plot_units",
                  label = "Units",
                  choices = c("px", "cm", "inch"),
                  selected = "cm",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::numericInput(
                  inputId = "summarise_log_file_plot_dpi",
                  label = "DPI",
                  value = 300
                ),
                shiny::downloadButton(outputId = "summarise_log_file_plot_download", label = "Download plot")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::materialSwitch(
                  inputId = "summarise_log_file_plot_interactive",
                  label = "Interactive",
                  value = TRUE
                ),
                shinyWidgets::pickerInput(
                  inputId = "summarise_log_file_plot_position",
                  label = "Columns",
                  choices = c("dodge", "stack"),
                  selected = "stack",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              shiny::uiOutput("summarise_log_file_plot") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.7.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
