# Generated by OmopViewer 0.7.0
# Be careful editing this file

library(bslib)
library(CohortCharacteristics)
library(DiagrammeR)
library(DiagrammeRsvg)
library(dplyr)
library(DT)
library(ggplot2)
library(gt)
library(markdown)
library(omopgenerics)
library(OmopSketch)
library(plotly)
library(purrr)
library(readr)
library(rlang)
library(rsvg)
library(shiny)
library(shinycssloaders)
library(shinyTree)
library(shinyWidgets)
library(sortable)
library(tidyr)
library(visOmopResults)
library(yaml)

# preprocess data if it has not been done
fileData <- file.path(getwd(), "data", "studyData.RData")
if (!file.exists(fileData)) {
  source(file.path(getwd(), "rawData", "preprocess.R"))
}
tidy_fit <- readr::read_csv(file.path(getwd(), "all_results.csv"), show_col_types = FALSE)
# uncomment to load the raw data
#a<- omopgenerics::importSummarisedResult(file.path(getwd(), "rawData"))
# b <- settings(a)|>mutate(table_name = case_when(table_name=="vaccine_washout" ~ "Vaccination records of the overall population",
#                                                  table_name=="vaccinated_within_campaigns" ~ "Vaccinated eligibles",
#                                                  table_name=="all_campaigns" ~ "Eligibles for vaccination"))
rawData <- omopgenerics::importSummarisedResult(file.path(getwd(), "rawData"))

# load shiny data
load(fileData)

# source functions
source(file.path(getwd(), "functions.R"))
